### PR TITLE
Reset Password Controller.

### PR DESCRIPTION
**Pull request by N3gus**
It just has comments for the fields we're going to be working on.

### CODE REVIEW

**Review by IttaiTumelo — APPROVED** [review]
lgtm

**Review by Giftstone — APPROVED** [review]

**Review by ReneW11 — APPROVED** [review]
reviewed

**Review by Giftstone — APPROVED** [review]
lgtm

**Review by Giftstone — APPROVED** [review]
lgtm

**Review by Giftstone — APPROVED** [review]
lgtm

**Review by Giftstone — APPROVED** [review]
lgtm

**Review by ReneW11 — APPROVED** [review]

**Review by ReneW11 — APPROVED** [review]

**Pull request merged**
